<a href="https://colab.research.google.com/github/murillo-borges/webscraping-livelo-esfera/blob/main/Webscraping_Whats_Milhas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [21]:
texto_bom_dia = """
☀️ *Bom dia, milheiros!* ✈️

Antes de começar o dia, segue a nossa escala de análise das promoções para você tomar decisões estratégicas no acúmulo de milhas:

Nós avaliamos cada promoção em 5 níveis, com base no retorno de milhas por real gasto:

• *Nível 1 (Ruim) ⚠️* → Sugiro aguardar algo melhor.
• *Nível 2 (Mediano) ⭐* → Use só se você já ia comprar de qualquer forma.
• *Nível 3 (Bom) ✨* → Bom para compras planejadas, mas ainda pode melhorar.
• *Nível 4 (Muito Bom) 🔥* → Ótima promoção. Daqui pra cima já vale muito a pena!
• *Nível 5 (Excelente / Raro) 🌟* → Promoção rara, dessas que não aparecem toda hora. Aproveite sem medo!

Quanto maior o nível, melhor o custo-benefício para acumular milhas.
Se aparecer *Nível 5*, estamos falando do *topo da escala* — ótima chance para turbinar o acúmulo com inteligência. 💰✈️

Vamos pra cima hoje! 🚀
"""

## Grupo de Beleza e Cosméticos

### Loja Natura

In [33]:
#pagina = requests.get('https://www.comparemania.com.br/cashback-amazon/')
pagina = requests.get('https://www.comparemania.com.br/cashback-natura/')
dados_pagina = BeautifulSoup(pagina.text, 'html.parser')

#Extraindo os nomes dos clubes
list_nomes_clubes = []
nomes_clubes = dados_pagina.find_all('div', class_='d-grid')
for div in nomes_clubes:
  texto_nome = div.find_all('div', class_='d-grid')
  for div in texto_nome:
    d_nome_clube = div.find('span').text
    if d_nome_clube == "Livelo":
      d_nome_clube = f'🟣 {d_nome_clube}'
    elif d_nome_clube == "Esfera":
      d_nome_clube = f'🔴 {d_nome_clube}'
    elif d_nome_clube == "Smiles":
      d_nome_clube = f'🟠 {d_nome_clube}'
    elif d_nome_clube in("Shopping Latam", "Azul"):
      d_nome_clube = f'🔵 {d_nome_clube}'

    list_nomes_clubes.append(d_nome_clube)
    print(d_nome_clube)


#Extraindo a pontuacao dos clubes
list_pontuacao_clubes = []
pontuacao_clubes = dados_pagina.find_all('span', class_='text-center lh-70')

for div in pontuacao_clubes:
  d_pontuacao_clube = div.text

  #Analise da pontuacao
  num_pontos = d_pontuacao_clube[:2]
  num_pontos = int(num_pontos.replace(",", ""))
  list_pontuacao_clubes.append(num_pontos)


# Criando o DataFrame Unificado
df_natura = pd.DataFrame({
    "nome_clube": list_nomes_clubes,
    "pontuacao_clube": list_pontuacao_clubes
})

list_analise_pontuacao = []

for index, row in df_natura.iterrows():
    #print(index, row["nome_clube"], row["pontuacao_clube"])

    #Igualando os pesos entre pontos e milhas (considerando uma promo de 80% de bônus)
    if row["nome_clube"] not in("Livelo","Esfera"):
      pontuacao_ajustada = row["pontuacao_clube"] / 1.8
    else:
      pontuacao_ajustada = row["pontuacao_clube"]

    #Analisando a promoção
    if pontuacao_ajustada >= 12:
      d_analise = '🟢 Nível 5 (Excelente / Raro) 🌟: Promoção rara, aproveite sem medo!'
    elif pontuacao_ajustada >= 8:
      d_analise = '🟢 Nível 4 (Muito Bom) 🔥: Ótima Promoção, daqui pra cima já vale muito!'
    elif pontuacao_ajustada >= 6:
      d_analise = '🟡 Nível 3 (Bom) ✨: Bom momento para potencializar compras planejadas, mas se puder aguardar, tem coisa melhor!'
    elif pontuacao_ajustada >= 3:
      d_analise = '🟡 Nível 2 (Mediano) ⭐: Dá pra usar se você realmente já ia comprar, mas é melhor aguardar algo melhor ;)'
    else:
      d_analise = '🔴 Nível 1 (Ruim) ⚠️: Sugiro aguardar algo melhor'

    list_analise_pontuacao.append(d_analise)


df_natura['analise_pontuacao'] = list_analise_pontuacao
df_natura['parceiro'] = 'Natura'
df_natura

🔴 Esfera
🟠 Smiles
🟣 Livelo
🔵 Azul
🔵 Shopping Latam

,nome_clube,pontuacao_clube,analise_pontuacao,parceiro
0,🔴 Esfera,12,🟡 Nível 3 (Bom) ✨: Bom momento para potenciali...,Natura
1,🟠 Smiles,4,🔴 Nível 1 (Ruim) ⚠️: Sugiro aguardar algo melhor,Natura
2,🟣 Livelo,4,🔴 Nível 1 (Ruim) ⚠️: Sugiro aguardar algo melhor,Natura
3,🔵 Azul,4,🔴 Nível 1 (Ruim) ⚠️: Sugiro aguardar algo melhor,Natura
4,🔵 Shopping Latam,3,🔴 Nível 1 (Ruim) ⚠️: Sugiro aguardar algo melhor,Natura

### Loja Boticário

In [43]:
#pagina = requests.get('https://www.comparemania.com.br/cashback-amazon/')
pagina = requests.get('https://www.comparemania.com.br/cashback-boticario/')
dados_pagina = BeautifulSoup(pagina.text, 'html.parser')

#Extraindo os nomes dos clubes
list_nomes_clubes = []
nomes_clubes = dados_pagina.find_all('div', class_='d-grid')
for div in nomes_clubes:
  texto_nome = div.find_all('div', class_='d-grid')
  for div in texto_nome:
    d_nome_clube = div.find('span').text
    if d_nome_clube == "Livelo":
      d_nome_clube = f'🟣 {d_nome_clube}'
    elif d_nome_clube == "Esfera":
      d_nome_clube = f'🔴 {d_nome_clube}'
    elif d_nome_clube == "Smiles":
      d_nome_clube = f'🟠 {d_nome_clube}'
    elif d_nome_clube in("Shopping Latam", "Azul"):
      d_nome_clube = f'🔵 {d_nome_clube}'

    list_nomes_clubes.append(d_nome_clube)
    print(d_nome_clube)

#Extraindo a pontuacao dos clubes
list_pontuacao_clubes = []
pontuacao_clubes = dados_pagina.find_all('span', class_='text-center lh-70')

for div in pontuacao_clubes:
  d_pontuacao_clube = div.text

  #Analise da pontuacao
  num_pontos = d_pontuacao_clube[:2]
  num_pontos = int(num_pontos.replace(",", ""))
  list_pontuacao_clubes.append(num_pontos)


df_boticario = pd.DataFrame({
    "nome_clube": list_nomes_clubes,
    "pontuacao_clube": list_pontuacao_clubes
})

list_analise_pontuacao = []

for index, row in df_boticario.iterrows():
    #print(index, row["nome_clube"], row["pontuacao_clube"])

    #Igualando os pesos entre pontos e milhas (considerando uma promo de 80% de bônus)
    if row["nome_clube"] not in("Livelo","Esfera"):
      pontuacao_ajustada = row["pontuacao_clube"] / 1.8
    else:
      pontuacao_ajustada = row["pontuacao_clube"]

    #Analisando a promoção
    if pontuacao_ajustada >= 12:
      d_analise = '🟢 Nível 5 (Excelente / Raro) 🌟: Promoção rara, aproveite sem medo!'
    elif pontuacao_ajustada >= 8:
      d_analise = '🟢 Nível 4 (Muito Bom) 🔥: Ótima Promoção, daqui pra cima já vale muito!'
    elif pontuacao_ajustada >= 6:
      d_analise = '🟡 Nível 3 (Bom) ✨: Bom momento para potencializar compras planejadas, mas se puder aguardar, tem coisa melhor!'
    elif pontuacao_ajustada >= 3:
      d_analise = '🟡 Nível 2 (Mediano) ⭐: Dá pra usar se você realmente já ia comprar, mas é melhor aguardar algo melhor ;)'
    else:
      d_analise = '🔴 Nível 1 (Ruim) ⚠️: Sugiro aguardar algo melhor'

    list_analise_pontuacao.append(d_analise)


df_boticario['analise_pontuacao'] = list_analise_pontuacao
df_boticario['parceiro'] = 'Boticario'
df_boticario

🟣 Livelo
🔴 Esfera

,nome_clube,pontuacao_clube,analise_pontuacao,parceiro
0,🟣 Livelo,6,🟡 Nível 2 (Mediano) ⭐: Dá pra usar se você rea...,Boticario
1,🔴 Esfera,2,🔴 Nível 1 (Ruim) ⚠️: Sugiro aguardar algo melhor,Boticario

### Concatenando os dataframes

In [34]:
df_final = pd.concat([df_natura, df_boticario], ignore_index=True)
df_final

,nome_clube,pontuacao_clube,analise_pontuacao,parceiro
0,🔴 Esfera,12,🟡 Nível 3 (Bom) ✨: Bom momento para potenciali...,Natura
1,🟠 Smiles,4,🔴 Nível 1 (Ruim) ⚠️: Sugiro aguardar algo melhor,Natura
2,🟣 Livelo,4,🔴 Nível 1 (Ruim) ⚠️: Sugiro aguardar algo melhor,Natura
3,🔵 Azul,4,🔴 Nível 1 (Ruim) ⚠️: Sugiro aguardar algo melhor,Natura
4,🔵 Shopping Latam,3,🔴 Nível 1 (Ruim) ⚠️: Sugiro aguardar algo melhor,Natura
5,🟣 Livelo,6,🟡 Nível 2 (Mediano) ⭐: Dá pra usar se você rea...,Boticario
6,🔴 Esfera,2,🔴 Nível 1 (Ruim) ⚠️: Sugiro aguardar algo melhor,Boticario

### Criando a mensagem do grupo de Beleza e Cosméticos

In [35]:
msg = ""
msg_titulo = "💄 *Promoções do Grupo de Beleza e Cosméticos:*"

for index, row in df_final.iterrows():
  msg += f"""
*Parceiro:* {row["parceiro"]}
*Programa de Fidelidade:* {row["nome_clube"]}
*Pontuação:* {row["pontuacao_clube"]}
*Análise da Promoção:* {row["analise_pontuacao"]}

{"-"*30}"""
  #print(msg)
    #print(index, row["nome_clube"], row["pontuacao_clube"])

msg_grupo = msg_titulo + "\n" + msg

In [36]:
print(msg_grupo)

💄 *Promoções do Grupo de Beleza e Cosméticos:*

*Parceiro:* Natura
*Programa de Fidelidade:* 🔴 Esfera
*Pontuação:* 12
*Análise da Promoção:* 🟡 Nível 3 (Bom) ✨: Bom momento para potencializar compras planejadas, mas se puder aguardar, tem coisa melhor!

------------------------------
*Parceiro:* Natura
*Programa de Fidelidade:* 🟠 Smiles
*Pontuação:* 4
*Análise da Promoção:* 🔴 Nível 1 (Ruim) ⚠️: Sugiro aguardar algo melhor

------------------------------
*Parceiro:* Natura
*Programa de Fidelidade:* 🟣 Livelo
*Pontuação:* 4
*Análise da Promoção:* 🔴 Nível 1 (Ruim) ⚠️: Sugiro aguardar algo melhor

------------------------------
*Parceiro:* Natura
*Programa de Fidelidade:* 🔵 Azul
*Pontuação:* 4
*Análise da Promoção:* 🔴 Nível 1 (Ruim) ⚠️: Sugiro aguardar algo melhor

------------------------------
*Parceiro:* Natura
*Programa de Fidelidade:* 🔵 Shopping Latam
*Pontuação:* 3
*Análise da Promoção:* 🔴 Nível 1 (Ruim) ⚠️: Sugiro aguardar algo melhor

------------------------------
*Parceiro:* Boticario
*Programa de Fidelidade:* 🟣 Livelo
*Pontuação:* 6
*Análise da Promoção:* 🟡 Nível 2 (Mediano) ⭐: Dá pra usar se você realmente já ia comprar, mas é melhor aguardar algo melhor ;)

------------------------------
*Parceiro:* Boticario
*Programa de Fidelidade:* 🔴 Esfera
*Pontuação:* 2
*Análise da Promoção:* 🔴 Nível 1 (Ruim) ⚠️: Sugiro aguardar algo melhor

------------------------------

### Enviando mensagem no grupo do Whatsapp

In [37]:
import requests

# Substitua com os dados reais
INSTANCE_ID = 'inst_4ng9578nwiz0'
API_KEY = 'sk_hRzCfVl0hSFebdFmmN0hwhpNZtVA9JqIdscEpatVHyreMM9f'

# JID do grupo (obtido via rota /groups)
group_jid = '555195564436-1477420627@g.us'

# Mensagem
message = msg_grupo

# Endpoint
url = f"https://api.zapperapi.com/{INSTANCE_ID}/messages/text"

# Payload
payload = {
    "jid": group_jid,
    "message": message,
}

headers = {
    "X-Api-Key": API_KEY,
    "Content-Type": "application/json"
}

response = requests.post(url, json=payload, headers=headers)

# Resposta
if response.status_code == 200:
    print("Mensagem enviada com sucesso para o grupo!")
else:
    print(f"Erro ao enviar mensagem: {response.status_code} - {response.text}")

Mensagem enviada com sucesso para o grupo!

### ADD SEPHORA E EPOCA

### ADD NETSHOES E CENTAURO

### ADD RENNER, C&A, RIACHUELO

In [168]:
### ADD MERCADO LIVRE, AMAZON, CASAS BAHIA, PONTO, MAGALU