<a href="https://colab.research.google.com/github/murillo-borges/webscraping-livelo-esfera/blob/main/Webscraping_Whats_Milhas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Dados padronizados

### Instalando Bibliotecas

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
pip install datetime

Requirement already satisfied: datetime in /usr/local/lib/python3.12/dist-packages (6.0)
Requirement already satisfied: zope.interface in /usr/local/lib/python3.12/dist-packages (from datetime) (8.2)
Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (from datetime) (2025.2)

### Importando Bibliotecas

In [ ]:
import requests
import pandas as pd
import re
import os
import datetime
import time
from bs4 import BeautifulSoup
from zoneinfo import ZoneInfo
import textwrap

### Horarios envios
- 08h
- 11h
- 14h
- 18h

In [ ]:
#Horarios de corte para envios
hora_max_grupo_perfumaria_cosmeticos = 10
hora_min_grupo_esportivo = 11
hora_max_grupo_esportivo = 12
hora_min_grupo_moda = 12
hora_max_grupo_moda = 14
hora_min_grupo_cosmeticos = 14
hora_max_grupo_cosmeticos = 15
hora_min_grupo_varejo = 17
hora_max_grupo_varejo = 18
hora_jabar_18 = 18
hora_jabar_11 = 11

### Definindo o ID do Grupo

In [ ]:
id_grupo_envio = os.environ['ID_GRUPO_MILHAS'] #os.environ['ID_GRUPO_PESSOAL_TESTES']

### Definindo os dados da API para envio no Whatsapp

In [ ]:
INSTANCE_ID = os.environ['INSTANCE_ID']
API_KEY = os.environ['API_KEY']

# Endpoint
url = f"https://api.zapperapi.com/{INSTANCE_ID}/messages/text" #url para mensagens de texto
url_media = f"https://api.zapperapi.com/{INSTANCE_ID}/messages/media" #url para mensagens de texto com imagens

headers = {
    "X-Api-Key": API_KEY,
    "Content-Type": "application/json"
}

KeyError: 'INSTANCE_ID'

### Função para Webscrapping

In [ ]:
#Coletando a data do dia
data_hoje = datetime.datetime.now(ZoneInfo("America/Sao_Paulo")).date()
data_formatada = data_hoje.strftime("%d/%m/%Y")

# Lista de nomes que você quer capturar (normalizados)
nomes_alvo = ["livelo", "shopping livelo", "esfera", "smiles", "azul", "shopping latam", "latam", "pass", "LATAM Pass", "Shopping Livelo"]

#Buscando a hora atual
agora_brasilia = datetime.datetime.now(ZoneInfo("America/Sao_Paulo"))

hora_atual = int(agora_brasilia.strftime("%H"))

def coletar_promocoes(url, parceiro, data_formatada, nomes_alvo):
    pagina = requests.get(url)
    dados_pagina = BeautifulSoup(pagina.text, 'html.parser')

    # --- Captura dos nomes ---
    list_nomes_clubes = []
    for sp in dados_pagina.select("div.d-grid span"):
        nome = sp.get_text(strip=True)
        nome_norm = nome.lower()

        if nome_norm not in nomes_alvo:
            continue

        # Emojis
        if nome_norm in("livelo", "Shopping Livelo"):
            nome = f"🟣 {nome}"
        elif nome_norm == "esfera":
            nome = f"🔴 {nome}"
        elif nome_norm == "smiles":
            nome = f"🟠 {nome}"
        elif nome_norm in ("azul", "shopping latam", "latam"):
            nome = f"🔵 {nome}"
        else:
            nome = nome

        list_nomes_clubes.append(nome)

    # --- Captura da pontuação ---
    list_pontuacao_clubes = []
    tabela_pm = dados_pagina.find('th', string=lambda s: s and 'Pontos e Milhas' in s)
    if tabela_pm:
        table = tabela_pm.find_parent('table')
        for tr in table.select('tbody tr'):
            nome_el = tr.select_one('td .d-grid span')
            if not nome_el:
                continue
            nome_norm = nome_el.get_text(strip=True).lower()

            if nome_norm not in nomes_alvo:
                continue

            tds = tr.find_all('td')
            if len(tds) < 2:
                continue

            texto_ganho = tds[-1].get_text(" ", strip=True)
            m = re.search(r'(\d+(?:[.,]\d+)?)\s*pt', texto_ganho, flags=re.I)
            if not m:
                continue

            valor = m.group(1).replace(',', '.')
            val_float = float(valor)
            val_final = int(val_float) if val_float.is_integer() else val_float

            list_pontuacao_clubes.append(val_final)

    # Monta DataFrame
    df = pd.DataFrame({
        "nome_clube": list_nomes_clubes,
        "pontuacao_clube": list_pontuacao_clubes
    })

    # --- Ajuste de pontuação e análise ---
    list_analise = []
    for index, row in df.iterrows():
        nome_norm = row["nome_clube"].lower()

        if ("livelo" not in nome_norm) and ("esfera" not in nome_norm):
            pontuacao_ajustada = row["pontuacao_clube"] / 1.8
        else:
            pontuacao_ajustada = row["pontuacao_clube"]

        #Analisando a promoção
        if pontuacao_ajustada >= 12:
          d_analise = '⭐⭐⭐⭐⭐ Nível 5 (Excelente / Raro) 😏: Promoção rara, aproveite sem medo!'
        elif pontuacao_ajustada >= 8:
          d_analise = '⭐⭐⭐⭐ Nível 4 (Muito Bom) 😎: Ótima Promoção, daqui pra cima já vale muito!'
        elif pontuacao_ajustada >= 6:
          d_analise = '⭐⭐⭐ Nível 3 (Bom) 😉: Bom momento para potencializar compras planejadas, mas se puder aguardar, tem coisa melhor!'
        elif pontuacao_ajustada >= 3:
          d_analise = '⭐⭐ Nível 2 (Mediano) 🧐: Dá pra usar se você realmente já iria comprar, mas é melhor aguardar algo melhor ;)'
        else:
          d_analise = '⭐ Nível 1 (Ruim) 😡: Sugiro aguardar algo melhor'

        list_analise.append(d_analise)

    df["analise_pontuacao"] = list_analise
    df["parceiro"] = parceiro
    df["data_coleta_promocao"] = data_formatada

    return df

### Mensagem Bom dia

In [ ]:
#Criando o texto de bom dia

dia_semana = agora_brasilia.strftime("%A")  # Nome do dia em inglês

if dia_semana == "Monday":
    txt_dia_semana = "segundou! 😴"
elif dia_semana == "Tuesday":
    txt_dia_semana = "terçou!"
elif dia_semana == "Wednesday":
    txt_dia_semana = "quartou!"
elif dia_semana == "Thursday":
    txt_dia_semana = "quintou! 🚀"
elif dia_semana == "Friday":
    txt_dia_semana = "sextou! 🔥"
elif dia_semana == "Saturday":
    txt_dia_semana = "sabadou! 😎"
elif dia_semana == "Sunday":
    txt_dia_semana = "domingou! ☀️"
else:
    txt_dia_semana = "vocês estão bem?"

texto_bom_dia = f"""
☀️ *Bom dia milheiros, {txt_dia_semana}*

Antes de começar o dia, segue o nosso critério de análise para você aproveitar as melhores promoções no acúmulo de milhas:

Nós avaliamos cada promoção em 5 níveis, com base no retorno de milhas/pontos:

• *Nível 1 (Ruim) ⭐* Menos que 3 pontos → Sugiro aguardar algo melhor.
• *Nível 2 (Mediano) ⭐⭐* 3 pontos ou mais → Use só se você já iria comprar de qualquer forma.
• *Nível 3 (Bom) ⭐⭐⭐* 6 pontos ou mais → Bom para compras planejadas, mas ainda pode melhorar.
• *Nível 4 (Muito Bom) ⭐⭐⭐⭐* 8 pontos ou mais → Ótima promoção, daqui pra cima já vale muito a pena!
• *Nível 5 (Excelente / Raro) ⭐⭐⭐⭐⭐* 12 pontos ou mais → Promoção rara, dessas que não aparecem toda hora. Aproveite sem medo!

Quanto maior o nível, melhor o custo-benefício para acumular milhas/pontos.

Obs: Em promoções diretamente nas cias aéreas, nos aplicamos uma divisão de 1,80 para igualar as milhas ao pontos (considerando
uma transferência bonificada de 80%)!

Se você está gostando das nossas análises, deixe o seu like nessa mensagem ;)

Ótimo dia a todos! Bora pra cima! 🚀

Att @murilloinvestor
"""

print(texto_bom_dia)

☀️ *Bom dia milheiros, terçou!*

Antes de começar o dia, segue o nosso critério de análise para você aproveitar as melhores promoções no acúmulo de milhas:

Nós avaliamos cada promoção em 5 níveis, com base no retorno de milhas/pontos:

• *Nível 1 (Ruim) ⭐* Menos que 3 pontos → Sugiro aguardar algo melhor.
• *Nível 2 (Mediano) ⭐⭐* 3 pontos ou mais → Use só se você já iria comprar de qualquer forma.
• *Nível 3 (Bom) ⭐⭐⭐* 6 pontos ou mais → Bom para compras planejadas, mas ainda pode melhorar.
• *Nível 4 (Muito Bom) ⭐⭐⭐⭐* 8 pontos ou mais → Ótima promoção, daqui pra cima já vale muito a pena!
• *Nível 5 (Excelente / Raro) ⭐⭐⭐⭐⭐* 12 pontos ou mais → Promoção rara, dessas que não aparecem toda hora. Aproveite sem medo!

Quanto maior o nível, melhor o custo-benefício para acumular milhas/pontos.

Obs: Em promoções diretamente nas cias aéreas, nos aplicamos uma divisão de 1,80 para igualar as milhas ao pontos (considerando
uma transferência bonificada de 80%)!

Se você está gostando das nossas análises, deixe o seu like nessa mensagem ;)

Ótimo dia a todos! Bora pra cima! 🚀

Att @murilloinvestor

## Grupo de Perfumaria (07h am)

### Loja Natura

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(7, 8):
    df_natura = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-natura/",
        parceiro="Natura",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_natura)
else:
    print("Fora do horário!")

Fora do horário!

### Loja Boticário

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(7, 8):
    df_boticario = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-boticario/",
        parceiro="Boticário",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_boticario)
else:
    print("Fora do horário!")

Fora do horário!

### Loja Eudora

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(7, 8):
    df_eudora = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-eudora/",
        parceiro="Eudora",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_eudora)
else:
    print("Fora do horário!")

Fora do horário!

### Enviando os dados via Whatsapp

In [ ]:
if hora_atual in(7, 8):
  # Concatenando os dataframes
  df_final = pd.concat([df_natura, df_boticario, df_eudora], ignore_index=True)
  df_final

  # Criando a mensagem do grupo de Beleza e Cosméticos
  msg = ""
  msg_titulo = f"💄 *Resumo das Promoções da Categoria de Perfumaria e Cosméticos em {data_formatada}: 👇*"

  for index, row in df_final.iterrows():
    msg += textwrap.dedent(f"""
  *Parceiro:* {row["parceiro"]}
  *Programa de Fidelidade:* {row["nome_clube"]}
  *Pontuação:* {row["pontuacao_clube"]}
  *Análise da Promoção:* {row["analise_pontuacao"]}

  {"-"*30}""").strip()

  msg_grupo = msg_titulo + "\n""\n" + msg

  # Mensagem de Bom dia
  message_bom_dia = texto_bom_dia
  message_promo = msg_grupo

  # Payload
  payload = {
      "jid": id_grupo_envio,
      "message": message_bom_dia,
  }

  #Enviando a mensagem de bom dia
  response = requests.post(url, json=payload, headers=headers)

  # Resposta
  if response.status_code == 200:
      print("Mensagem de bom dia enviada com sucesso para o grupo!")
  else:
      print(f"Erro ao enviar mensagem: {response.status_code} - {response.text}")


  # Aguardar 2 minutos
  time.sleep(120)

  # Payload
  payload = {
      "jid": id_grupo_envio, #group_jid,
      "message": message_promo,
  }

  #Enviando as promoções
  response = requests.post(url, json=payload, headers=headers)

  # Resposta
  if response.status_code == 200:
      print("Mensagem com as promoções enviada com sucesso para o grupo!")
  else:
      print(f"Erro ao enviar mensagem: {response.status_code} - {response.text}")

else:
  print("Fora do horário!")

Fora do horário!

##

## Grupo de Roupas e Calçados Esportivos (09h am) GRUPO OK

### Loja Centauro

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(9, 10):
    df_centauro = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-centauro/",
        parceiro="Centauro",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_centauro)
else:
    print("Fora do horário!")

Fora do horário!

### Loja NetShoes

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(9, 10):
    df_netshoes = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-netshoes/",
        parceiro="Netshoes",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_netshoes)
else:
    print("Fora do horário!")

Fora do horário!

### Loja New Balance

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(9, 10):
    df_new_balance = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-new-balance/",
        parceiro="New Balance",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_new_balance)
else:
    print("Fora do horário!")

Fora do horário!

### Loja Nike

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(9, 10):
    df_nike = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-nike/",
        parceiro="Nike",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_nike)
else:
    print("Fora do horário!")

Fora do horário!

### Loja Adidas

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(9, 10):
    df_adidas = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-adidas/",
        parceiro="Adidas",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_adidas)
else:
    print("Fora do horário!")

Fora do horário!

### Enviando os dados via Whatsapp

In [ ]:
if hora_atual in(9, 10):
  # Concatenando os dataframes
  df_final = pd.concat([df_centauro, df_netshoes, df_new_balance, df_nike, df_adidas], ignore_index=True)
  df_final

  # Criando a mensagem do grupo de Beleza e Cosméticos
  msg = ""
  msg_titulo = f"👟🏓 *Promoções da Categoria de Roupas e Calçados Esportivos em {data_formatada}: 👇*"

  for index, row in df_final.iterrows():
    msg += textwrap.dedent(f"""
  *Parceiro:* {row["parceiro"]}
  *Programa de Fidelidade:* {row["nome_clube"]}
  *Pontuação:* {row["pontuacao_clube"]}
  *Análise da Promoção:* {row["analise_pontuacao"]}

  {"-"*30}""").strip()

  msg_grupo = msg_titulo + "\n\n" + msg

  # Mensagem
  message_promo = msg_grupo

  # Payload
  payload = {
      "jid": id_grupo_envio, #group_jid,
      "message": message_promo,
  }

  #Enviando as promoções
  response = requests.post(url, json=payload, headers=headers)

  # Resposta
  if response.status_code == 200:
      print("Mensagem com as promoções enviada com sucesso para o grupo!")
  else:
      print(f"Erro ao enviar mensagem: {response.status_code} - {response.text}")

else:
  print("Fora do horário!")

Fora do horário!

## Grupo de Moda (11h am)

### Loja Renner

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(11, 12):
    df_renner = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-lojas-renner/",
        parceiro="Lojas Renner",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_renner)
else:
    print("Fora do horário!")

Fora do horário!

### Loja Riachuelo

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(11, 12):
    df_riachuelo = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-riachuelo/",
        parceiro="Riachuelo",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_riachuelo)
else:
    print("Fora do horário!")

Fora do horário!

### Loja CEA

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(11, 12):
    df_cea = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-cea/",
        parceiro="CEA",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_cea)
else:
    print("Fora do horário!")

Fora do horário!

### Loja Hering

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(11, 12):
    df_hering = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-hering/",
        parceiro="CEA",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_hering)
else:
    print("Fora do horário!")

Fora do horário!

### Loja Dafiti

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(11, 12):
    df_dafiti = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-dafiti/",
        parceiro="Dafiti",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_dafiti)
else:
    print("Fora do horário!")

Fora do horário!

### Enviando os dados via Whatsapp

In [ ]:
if hora_atual in(11, 12):

  # Concatenando os dataframes
  df_final = pd.concat([df_renner, df_riachuelo, df_cea, df_hering, df_dafiti], ignore_index=True)

  # Criando a mensagem do grupo de Beleza e Cosméticos
  msg = ""
  msg_titulo = f"👗👔 *Promoções da Categoria de Moda em {data_formatada}: 👇*"

  for index, row in df_final.iterrows():
    msg += textwrap.dedent(f"""
  *Parceiro:* {row["parceiro"]}
  *Programa de Fidelidade:* {row["nome_clube"]}
  *Pontuação:* {row["pontuacao_clube"]}
  *Análise da Promoção:* {row["analise_pontuacao"]}

  {"-"*30}""").strip()

  msg_grupo = msg_titulo + "\n\n" + msg

  # Mensagem
  message_promo = msg_grupo

  # Payload
  payload = {
      "jid": id_grupo_envio,
      "message": message_promo,
  }

  #Enviando as promoções
  response = requests.post(url, json=payload, headers=headers)

  # Resposta
  if response.status_code == 200:
      print("Mensagem com as promoções enviada com sucesso para o grupo!")
  else:
      print(f"Erro ao enviar mensagem: {response.status_code} - {response.text}")

  display(df_final)

else:
  print("Fora do horário!")

Fora do horário!

## Grupo de Beleza e Cosméticos (13h am)

### Loja Beleza na Web

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(13, 14):
    df_beleza_web = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-beleza-na-web/",
        parceiro="Beleza na Web",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_beleza_web)
else:
    print("Fora do horário!")

Fora do horário!

### Loja Época Cosméticos

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(13, 14):
    df_epoca_cosmeticos = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-epoca-cosmeticos/",
        parceiro="Época Cosméticos",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_epoca_cosmeticos)
else:
    print("Fora do horário!")

Fora do horário!

### Loja Sephora

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(13, 14):
    df_sephora = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-sephora/",
        parceiro="Sephora",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_sephora)
else:
    print("Fora do horário!")

Fora do horário!

### Loja Oceane

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(13, 14):
    df_oceane = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-oceane/",
        parceiro="Oceane",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_oceane)
else:
    print("Fora do horário!")

Fora do horário!

### Enviando os dados via Whatsapp

In [ ]:
if hora_atual in(13, 14):
  # Concatenando os dataframes
  df_final = pd.concat([df_beleza_web, df_epoca_cosmeticos, df_sephora, df_oceane], ignore_index=True)

  # Criando a mensagem do grupo de Beleza e Cosméticos
  msg = ""
  msg_titulo = f"💄 *Resumo das Promoções da Categoria de Beleza e Cosméticos em {data_formatada}: 👇*"

  for index, row in df_final.iterrows():
    msg += textwrap.dedent(f"""
  *Parceiro:* {row["parceiro"]}
  *Programa de Fidelidade:* {row["nome_clube"]}
  *Pontuação:* {row["pontuacao_clube"]}
  *Análise da Promoção:* {row["analise_pontuacao"]}

  {"-"*30}""").strip()

  msg_grupo = msg_titulo + "\n""\n" + msg

  # Mensagem
  message_promo = msg_grupo

  # Payload
  payload = {
      "jid": id_grupo_envio,
      "message": message_promo,
  }

  #Enviando as promoções
  response = requests.post(url, json=payload, headers=headers)

  # Resposta
  if response.status_code == 200:
      print("Mensagem com as promoções enviada com sucesso para o grupo!")
  else:
      print(f"Erro ao enviar mensagem: {response.status_code} - {response.text}")

  display(df_final)

else:
  print("Fora do horário!")

Fora do horário!

## Grupo de Varejo (15h am)

### Loja Amazon (Latam pass nao esta aparecendo)

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(15, 16):
    df_kabum = coletar_promocoes(
        url="comparemania.com.br/cashback-kabum/",
        parceiro="Amazon",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_kabum)
else:
    print("Fora do horário!")

,nome_clube,pontuacao_clube,analise_pontuacao,parceiro,data_coleta_promocao
0,🔴 Esfera,1,⭐ Nível 1 (Ruim) 😡: Sugiro aguardar algo melhor,Amazon,02/02/2026
1,🟣 Livelo,1,⭐ Nível 1 (Ruim) 😡: Sugiro aguardar algo melhor,Amazon,02/02/2026

### Loja Ponto

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(15, 16):
    df_ponto = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-ponto/",
        parceiro="Ponto",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_ponto)
else:
    print("Fora do horário!")

,nome_clube,pontuacao_clube,analise_pontuacao,parceiro,data_coleta_promocao
0,🟣 Livelo,5,⭐⭐ Nível 2 (Mediano) 🧐: Dá pra usar se você re...,Ponto,02/02/2026
1,🔵 Azul,2,⭐ Nível 1 (Ruim) 😡: Sugiro aguardar algo melhor,Ponto,02/02/2026
2,🔴 Esfera,1,⭐ Nível 1 (Ruim) 😡: Sugiro aguardar algo melhor,Ponto,02/02/2026

### Loja Casas Bahia

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(15, 16):
    df_casas_bahia = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-casas-bahia/",
        parceiro="Casas Bahia",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_casas_bahia)
else:
    print("Fora do horário!")

,nome_clube,pontuacao_clube,analise_pontuacao,parceiro,data_coleta_promocao
0,🔴 Esfera,6,⭐⭐⭐ Nível 3 (Bom) 😉: Bom momento para potencia...,Casas Bahia,02/02/2026
1,🟣 Livelo,5,⭐⭐ Nível 2 (Mediano) 🧐: Dá pra usar se você re...,Casas Bahia,02/02/2026
2,🔵 Azul,2,⭐ Nível 1 (Ruim) 😡: Sugiro aguardar algo melhor,Casas Bahia,02/02/2026

### Loja Extra

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(15, 16):
    df_extra = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-extra/",
        parceiro="Extra",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_extra)
else:
    print("Fora do horário!")

,nome_clube,pontuacao_clube,analise_pontuacao,parceiro,data_coleta_promocao
0,🔴 Esfera,6,⭐⭐⭐ Nível 3 (Bom) 😉: Bom momento para potencia...,Extra,02/02/2026
1,🟣 Livelo,5,⭐⭐ Nível 2 (Mediano) 🧐: Dá pra usar se você re...,Extra,02/02/2026
2,🔵 Azul,2,⭐ Nível 1 (Ruim) 😡: Sugiro aguardar algo melhor,Extra,02/02/2026

### Loja Magalu

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(15, 16):
    df_magalu = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-magazine-luiza/",
        parceiro="Magalu",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_magalu)
else:
    print("Fora do horário!")

,nome_clube,pontuacao_clube,analise_pontuacao,parceiro,data_coleta_promocao
0,🔵 Azul,14,⭐⭐⭐ Nível 3 (Bom) 😉: Bom momento para potencia...,Magalu,02/02/2026
1,🟣 Livelo,4,⭐⭐ Nível 2 (Mediano) 🧐: Dá pra usar se você re...,Magalu,02/02/2026
2,🔴 Esfera,1,⭐ Nível 1 (Ruim) 😡: Sugiro aguardar algo melhor,Magalu,02/02/2026

### Loja Mercado Livre

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(15, 16):
    df_mercado_livre = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-mercado-livre/",
        parceiro="Mercado Livre",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_mercado_livre)
else:
    print("Fora do horário!")

,nome_clube,pontuacao_clube,analise_pontuacao,parceiro,data_coleta_promocao
0,🟣 Livelo,2,⭐ Nível 1 (Ruim) 😡: Sugiro aguardar algo melhor,Mercado Livre,02/02/2026

### Loja FastShop

In [ ]:
hora_atual = agora_brasilia.hour

if hora_atual in(15, 16):
    df_fast_shop = coletar_promocoes(
        url="https://www.comparemania.com.br/cashback-fast-shop/",
        parceiro="Fast Shop",
        data_formatada=data_formatada,
        nomes_alvo=nomes_alvo
    )
    display(df_fast_shop)
else:
    print("Fora do horário!")

,nome_clube,pontuacao_clube,analise_pontuacao,parceiro,data_coleta_promocao
0,🟣 Livelo,2,⭐ Nível 1 (Ruim) 😡: Sugiro aguardar algo melhor,Fast Shop,02/02/2026
1,🔴 Esfera,2,⭐ Nível 1 (Ruim) 😡: Sugiro aguardar algo melhor,Fast Shop,02/02/2026

### Enviando os dados via Whatsapp

In [ ]:
if hora_atual in(15, 16):

  # Concatenando os dataframes
  df_final = pd.concat([df_kabum, df_mercado_livre, df_magalu, df_ponto, df_casas_bahia, df_extra, df_fast_shop], ignore_index=True)
  df_final

  # Criando a mensagem do grupo de Beleza e Cosméticos
  msg = ""
  msg_titulo = f"📱💻 *Promoções do Grupo de Varejo em {data_formatada}: 👇*"

  for index, row in df_final.iterrows():
    msg += textwrap.dedent(f"""
  *Parceiro:* {row["parceiro"]}
  *Programa de Fidelidade:* {row["nome_clube"]}
  *Pontuação:* {row["pontuacao_clube"]}
  *Análise da Promoção:* {row["analise_pontuacao"]}

  {"-"*30}""").strip()

  msg_grupo = msg_titulo + "\n""\n" + msg

  # Mensagem
  message_promo = msg_grupo

  # Payload
  payload = {
      "jid": id_grupo_envio, #group_jid,
      "message": message_promo,
  }

  #Enviando as promoções
  response = requests.post(url, json=payload, headers=headers)

  # Resposta
  if response.status_code == 200:
      print("Mensagem com as promoções enviada com sucesso para o grupo!")
  else:
      print(f"Erro ao enviar mensagem: {response.status_code} - {response.text}")

else:
  print("Fora do horário!")

Mensagem com as promoções enviada com sucesso para o grupo!

## Jabares das 11h am (Mensagens com Imagens)

### Jabar banco inter (11h am Quarta e Sábado) GRUPO OK

In [ ]:
if hora_atual in(11, 12) and dia_semana in ("Wednesday", "Saturday"):

  # Aguardar 2 minutos
  time.sleep(120)

  if dia_semana == "Wednesday":
    message_promo = textwrap.dedent("""
    *Quer começar no mundo dos cartões com o pé direito?*

    O Inter Prime é uma ótima escolha: pontua bem, os pontos não expiram e você ainda
    ganha acesso às Salas VIP de forma gratuita, perfeito para dar um upgrade nas suas viagens.

    Lembrando que a forma mais fácil de conseguir esse cartão é *assinando o plano Duo Gourmet anual* 👇

    💰 *Quer economizar até R$50 no plano anual do Duo Gourmet?*

    Utilize o código B1EE1054 para ganhar até R$ 50 off na assinatura do plano anual pelo app do Inter!
    👉 Acesse: https://intergo.app/1f148152

    🟠 *Abra a sua conta no Banco Inter com o nosso link e ganhe 200 pontos*

    Utilize o código OW1AIMUA e abra a sua conta gratuita no Inter. Ao fazer isso, você já receberá 200 pontos Loop de presente!
    👉 https://inter-co.onelink.me/Qyu7/ste2n6tb

    -----------------------------

    💳 Não conhece esse cartão? Assista o vídeo abaixo para conhecer os principais benefícios do cartão Inter Prime 👇
    https://www.youtube.com/watch?v=laEm4960klw&list=PLywCMnijM298ruCE-Cey18WvsoV2UqqQf&index=1""").strip()

  else:
    message_promo = textwrap.dedent("""
    *Pensando em começar no mundo dos cartões? 💳*

    O Inter Prime é uma excelente opção: boa pontuação, pontos que não expiram e acesso às Salas VIP ✈️🔥

    A maneira mais simples de conseguir esse cartão é assinando o plano Duo Gourmet anual 👇

    💰 *Quer economizar até R$50 no plano anual do Duo Gourmet?*
    Use o código **B1EE1054** no app do Inter
    👉 https://intergo.app/1f148152

    🟠 *Ainda não tem conta? abra sua conta no Banco Inter e ganhe 200 pontos Loop*
    Use o código **OW1AIMUA**
    👉 https://inter-co.onelink.me/Qyu7/ste2n6tb

    -----------------------------

    💳 Conheça os benefícios do cartão Inter Prime:
    https://www.youtube.com/watch?v=laEm4960klw&list=PLywCMnijM298ruCE-Cey18WvsoV2UqqQf&index=1""").strip()

  drive_id = "1OpOK2Ee1q2yJO-UDhfP3w3hFh2uM7y0s"
  img_url = f"https://drive.google.com/uc?export=view&id={drive_id}"

  payload = {
      "jid": id_grupo_envio, #group_jid,
      "mediaType": "image",
      "mimetype": "image/jpeg",
      "media": img_url,
      "caption": message_promo,  # ← usa seu texto de análise
      "filename": "analise.jpg"
  }

  response = requests.post(url_media, json=payload, headers=headers)

  print(response.json())

else:
  print("Fora do horário!")

Fora do horário!

### Jabar planilha (11h am Quinta e Sexta) GRUPO OK

In [ ]:
if hora_atual in(11, 12) and dia_semana in ("Thursday", "Sunday"):

  # Aguardar 2 minutos
  time.sleep(120)

  if dia_semana == "Thursday":
    message_promo = textwrap.dedent("""
    *Quer organizar suas finanças de um jeito simples e inteligente?*

    A nossa Planilha de Controle Financeiro foi feita para quem quer parar de gastar no automático
    e finalmente entender para onde o dinheiro está indo, de forma clara, rápida e sem complicação.

    Por que essa planilha é a solução perfeita para você?
    • Simples de usar e totalmente automatizada
    • Visão completa do seu fluxo de caixa
    • Dashboard visual e intuitivo

    💡 *E o melhor?*
    • Ela custa menos do que uma pizza 🍕
    • Você paga *uma única vez* e fica com a planilha *para sempre*.
    • E você ainda ganha uma aula passo a passo. Mesmo sem saber Excel, você vai conseguir usar sem dificuldade. 🎓✅
    • Ao adquirir, você ainda apoia o nosso trabalho e nos ajuda a continuar trazendo conteúdo gratuito aqui no grupo. 🙏

    👉 Assista ao vídeo e adquira sua planilha aqui:
    https://bit.ly/whatsplancontrolefinanceiro

    -----------------------------

    🧠 *Organização financeira muda tudo.*
    Comece hoje, seu “eu do futuro” vai agradecer.""").strip()
  else:
    message_promo = textwrap.dedent("""
    *Quer organizar suas finanças de um jeito simples?*

    Nossa Planilha de Controle Financeiro te ajuda a ver para onde seu dinheiro está indo e a controlar seus gastos sem complicação.

    • Custa menos que uma pizza 🍕
    • Pagou uma vez, é sua para sempre.
    • E tem aula passo a passo (mesmo se você não souber Excel). 🎓✅

    👉 Conheça e adquira aqui:
    https://bit.ly/whatsplancontrolefinanceiro""").strip()


  # Imagem do Google Drive
  drive_id = "1dHHTOXW8g3bZ4AGZk14Lvnu9mGSpHoVc"
  img_url = f"https://drive.google.com/uc?export=view&id={drive_id}"

  payload = {
      "jid": id_grupo_envio, #group_jid,
      "mediaType": "image",
      "mimetype": "image/jpeg",
      "media": img_url,
      "caption": message_promo,  # ← usa seu texto de análise
      "filename": "analise.jpg"
  }

  response = requests.post(url_media, json=payload, headers=headers)

  print(response.json())

else:
  print("Fora do horário!")

Fora do horário!

### Jabar TopCashback (11h am Segunda e Quinta)

In [ ]:
if hora_atual in(11, 12) and dia_semana in ("Monday", "Thursday"):

  #Aguardar 45 segundos
  time.sleep(45)

  if dia_semana == "Monday":

    #Imagem do Google Drive
    drive_id = "1sVCoiFDKu0gbioPQSpZbOVkGbq6NYb8X" #Imagem de Segunda
    img_url = f"https://drive.google.com/uc?export=view&id={drive_id}"

  else:

    #Imagem do Google Drive
    drive_id = "1idhL58jQID5wemKh0XoHfqROn7L3MzTK" #Imagem de Quinta
    img_url = f"https://drive.google.com/uc?export=view&id={drive_id}"

  message_promo = textwrap.dedent("""
  🇬🇧 *Vai viajar ou reservar serviços no exterior? Então presta atenção nisso 👇*

  Alguns parceiros como o ALL por exemplo, permitem reservas no Brasil 🇧🇷

  Se você ainda não tem conta no *TopCashBack do Reino Unido*, vale muito a pena abrir.

  Usando o nosso link, você ainda pode ganhar um *bônus após a primeira compra* 💷✨

  👉 Abra sua conta aqui:
  https://bit.ly/topcashbackreinounido

  -----------------------------

  🏨 *Hospedagens com Cashback em Libra Esterlina:*
  • ALL Accor Live Limitless – até *15% de cashback*
    https://www.topcashback.co.uk/all-accor-live-limitless/

  • Hotels_com – até *15% de cashback*
    https://www.topcashback.co.uk/hotelscom/

  • Expedia – até *8,5% de cashback*
    https://www.topcashback.co.uk/search/merchants/?s=Expedia

  • Agoda – até *4% de cashback*
    https://www.topcashback.co.uk/search/merchants/?s=Agoda

  • Lastminute – até *8,5% de cashback*
    https://www.topcashback.co.uk/search/merchants/?s=lastminute.com

  -----------------------------

  🚗 *Locadoras de Carros com Cashback em Libra Esterlina:*
  • Avis – até *9,35% de cashback*
    https://www.topcashback.co.uk/search/merchants/?s=Avis

  • Discover Cars – até *25,5% de cashback*
    https://www.topcashback.co.uk/discover-car-hire/

  • Europcar – até *11,47% de cashback*
    https://www.topcashback.co.uk/europcar/

  • Sixt UK – até *8,5% de cashback*
    https://www.topcashback.co.uk/sixt-uk/

  • Alamo – até *4,25% de cashback*
    https://www.topcashback.co.uk/alamo/

  -----------------------------

  🚆 *Trem, Ferry e Ônibus com Cashback em Libra Esterlina:*
  • Omio – até *4,25% de cashback*
    https://www.topcashback.co.uk/omio/

  -----------------------------

  🎟️ *Passeios e Atrações com Cashback em Libra Esterlina:*
  • GetYourGuide – até *11% de cashback*
    https://www.topcashback.co.uk/getyourguide/

  • Groupon – até *5,95% de cashback*
    https://www.topcashback.co.uk/groupon/

  • Tripadvisor – até *12% de cashback*
    https://www.topcashback.co.uk/tripadvisor-tours-and-experiences/

  • Disneyland Paris – até *£42.50 de cashback*
    https://www.topcashback.co.uk/disneyland-resort-paris/

  -----------------------------

  ⚠️ *Importante:* sempre leia os termos do cashback antes de comprar.

  ‼️ O percentual pode variar diariamente e cada parceiro possui regras específicas para a validação do retorno.
    """).strip()


  message_promo2 = textwrap.dedent("""
  🇺🇸 *Além do TopCashBack Britânico, também existe o TopCashBack Americano 👇*

  Por isso, a melhor estratégia é sempre consultar os dois sites e comparar qual deles está oferecendo o *maior cashback no momento*.

  Em muitos casos, a diferença pode ser bem relevante 💰

  Alguns parceiros permitem reservas mesmo estando no Brasil 🇧🇷, o que pode gerar cashback em dólar de forma bem interessante 💵

  Se você ainda não tem conta no *TopCashBack dos Estados Unidos*, vale muito a pena abrir.
  Usando o nosso link, você ainda pode ganhar um *bônus após a primeira compra* ✨

  👉 Abra sua conta aqui:
  https://bit.ly/topcashbackamericano

  -----------------------------

  🏨 *Hospedagens*
  • ALL Accor – até *15% de cashback*
    https://www.topcashback.com/accorhotels/

  • Booking – até *10% de cashback*
    https://www.topcashback.com/booking-com/

  • Hotels.com – até *15% de cashback*
    https://www.topcashback.com/hotels-com/

  • Expedia – até *8,5% de cashback*
    https://www.topcashback.com/expedia/

  • Agoda – até *4% de cashback*
    https://www.topcashback.com/agoda/

  -----------------------------

  🚗 *Locadoras de Carros*
  • Avis – até *9,35% de cashback*
    https://www.topcashback.com/avis-rent-a-car/

  • Hertz – até *5% de cashback*
    https://www.topcashback.com/hertz/

  • Europcar – até *9% de cashback*
    https://www.topcashback.com/europcar/

  • Sixt – até *8% de cashback*
    https://www.topcashback.com/sixt/

  • Alamo – até *3% de cashback*
    https://www.topcashback.com/alamo-rent-a-car/

  -----------------------------

  🚆 *Trem, Ferry e Ônibus*
  • Omio – até *10% de cashback*
    https://www.topcashback.com/omio/

  -----------------------------

  🎟️ *Passeios e Atrações*
  • GetYourGuide – até *7% de cashback*
    https://www.topcashback.com/getyourguide/

  • Groupon – até *4% de cashback*
    https://www.topcashback.com/groupon/

  • Viator – até *15% de cashback*
    https://www.topcashback.com/viator/

  • Tripadvisor – até *10% de cashback*
    https://www.topcashback.com/tripadvisor-hotels/

  -----------------------------

  ⚠️ *Importante:* sempre leia os termos do cashback antes de comprar.

  ‼️ O percentual pode variar diariamente e cada parceiro possui regras específicas para a validação do retorno.
  """).strip()


  #Mensagem 1
  payload = {
      "jid": id_grupo_envio,
      "mediaType": "image",
      "mimetype": "image/jpeg",
      "media": img_url,
      "caption": message_promo,
      "filename": "analise.jpg"
  }

  headers = {
      "X-Api-Key": API_KEY,
      "Content-Type": "application/json"
  }

  response = requests.post(url_media, json=payload, headers=headers)

  #Aguardar 20 segundos
  time.sleep(20)


  #Mensagem 2
  message_promo = message_promo2

  payload = {
      "jid": id_grupo_envio,
      "message": message_promo,
  }

  response = requests.post(url, json=payload, headers=headers)

  print("Mensagem enviada!")

  #Aguardar 20 segundos
  time.sleep(20)


  #Mensagem 3
  message_promo3 = textwrap.dedent("""
    📺 *Quer aprender a usar o TopCashBack do jeito certo e extrair o máximo de cashback?*

    No nosso canal do YouTube temos uma *playlist completa* dedicada ao TopCashBack, onde mostramos passo a passo como usar a plataforma, dicas práticas, cuidados importantes e estratégias para aumentar seus ganhos 💰

    É conteúdo ideal tanto para quem está começando quanto para quem já usa e quer melhorar os resultados.

    👉 Assista à playlist completa aqui:
    https://www.youtube.com/playlist?list=PLywCMnijM298Xa4SBJ7w4aQK_qsxgG5nJ
  """).strip()

  message_promo = message_promo3

  payload = {
      "jid": id_grupo_envio,
      "message": message_promo,
  }

  response = requests.post(url, json=payload, headers=headers)

else:
  print("Fora do horário!")

Fora do horário!

## Jabares das 19h pm (Mensagens com Imagens)

### Jabar cartao Ruby Stell (19h Terça-Feira e Sexta-Feira)

In [ ]:
if hora_atual in(19,20) and dia_semana in ("Tuesday", "Friday"):

  # Aguardar 1 minuto
  time.sleep(60)

  if dia_semana == "Friday":

    # Imagem do Google Drive
    drive_id = "1EV2mu8AfLkIzo9dM23nP58e5lN7bYN18" #Imagem de Sexta
    img_url = f"https://drive.google.com/uc?export=view&id={drive_id}"

    message_promo = textwrap.dedent("""
    *Vai viajar para fora do Brasil ou fazer uma compra internacional? Então presta atenção nisso 👇*

    O *Cartão Crypto Ruby* é simplesmente um dos melhores cartões para uso internacional, porque:
    • Não cobra IOF nas compras (3,5% de economia) 🌍
    • Tem spread super baixo 💱
    • *2% de cashback* em todas as compras 💸
    • Spotify grátis 🎧

    Ou seja: você gasta menos, economiza nas taxas e ainda recebe dinheiro de volta.

    -----------------------------

    💳 *Quer ver esse cartão funcionando na prática?*
    Eu testei esse cartão por 15 dias e gravei um vídeo mostrando como usar, benefícios e pontos de atenção 👇
    https://www.youtube.com/watch?v=OA7LlqiobHQ&t=300s

    -----------------------------

    🔵 Gostou do cartão?
    Abra sua conta na Crypto com o nosso link e ganhe até **$60 USD** de bônus 💵
    👉 https://bit.ly/wcryptoruby

    """).strip()

  else:

    # Imagem do Google Drive
    drive_id = "1eLpOE5cJJe2ahFIMbbY1do2RSE-adggr" #Imagem de Terça
    img_url = f"https://drive.google.com/uc?export=view&id={drive_id}"

    message_promo = textwrap.dedent("""
    *Se você vai viajar ou costuma comprar fora do Brasil, esse cartão pode te fazer economizar MUITO* ✈️💸

    O *Crypto Ruby* é um dos poucos cartões que realmente vale a pena no uso internacional:

    • Zero IOF nas compras (economia 3,5%) 🌍
    • Spread super baixo (conversão mais justa) 💱
    • *2% de cashback* em tudo que você gastar 💸
    • Spotify grátis 🎧

    👀 *Spoiler:* ele tem um custo muito menor que vários cartões globais famosos do mercado.

    -----------------------------

    🎥 *Quer ver como ele funciona na prática?*
    Eu usei esse cartão e gravei um vídeo mostrando tudo:
    https://www.youtube.com/watch?v=OA7LlqiobHQ&t=300s

    -----------------------------

    🔵 Curtiu a ideia?
    Abra sua conta pela Crypto e ganhe até *$60 USD* de bônus 💵
    👉 https://bit.ly/wcryptoruby
    """).strip()

  payload = {
      "jid": id_grupo_envio, #group_jid,
      "mediaType": "image",
      "mimetype": "image/jpeg",
      "media": img_url,
      "caption": message_promo,
      "filename": "analise.jpg"
  }

  headers = {
      "X-Api-Key": API_KEY,
      "Content-Type": "application/json"
  }

  response = requests.post(url_media, json=payload, headers=headers)

  print("Mensagem enviada!")

else:
  print("Fora do horário!")

Fora do horário!

### Jabar Passeios Get Your Guide (19h Segunda-Feira e quinta-Feira)

In [ ]:
if hora_atual in(19,20) and dia_semana in ("Monday", "Thursday"):

    # Aguardar 5 segundos
    time.sleep(5)

    drive_id = "1F3Hq6nsn4fzS5KwZy4Addf65sY1AW7AG"
    img_url = f"https://drive.google.com/uc?export=view&id={drive_id}"

    if dia_semana == "Monday":
        message_promo = textwrap.dedent("""
        🌍 *Quer transformar sua viagem em uma experiência inesquecível?*

        No Get Your Guide você encontra os melhores passeios, tours e experiências em destinos do mundo todo — tudo em um só lugar! 🗺️

        🎯 City tours, passeios de barco, experiências gastronômicas, trilhas, museus e muito mais, em centenas de destinos pelo mundo.

        👉 *Acesse nossas recomendações e escolha o passeio perfeito para a sua próxima viagem:*
        https://www.getyourguide.com/explorer/creators/-cs4294

        💰 *Primeira reserva? Use o cupom abaixo e ganhe 5% de desconto:*
        🎟️ Cupom: *MURILLOINVESTOR5*

        -----------------------------

        ✈️ Viagem planejada é viagem aproveitada. Garante já o seu passeio!
        """).strip()

    else:  # Thursday
        message_promo = textwrap.dedent("""
        ✈️ *Já tem viagem marcada? Então esse conteúdo é pra ti!*

        No Get Your Guide tu encontras passeios incríveis em destinos do mundo todo — desde city tours clássicos até experiências únicas que vão fazer a tua viagem ser ainda mais especial 🌍🔥

        🗺️ Temos opções separadas por país pra facilitar a tua busca!

        👉 *Dá uma olhada nas nossas recomendações:*
        https://www.getyourguide.com/explorer/creators/-cs4294

        💰 *Na tua primeira reserva, usa o cupom abaixo e garante 5% de desconto:*
        🎟️ *MURILLOINVESTOR5*

        -----------------------------

        🌟 Experiências boas não acontecem por acaso — elas são planejadas!
        """).strip()

    payload = {
        "jid": id_grupo_envio,
        "mediaType": "image",
        "mimetype": "image/jpeg",
        "media": img_url,
        "caption": message_promo,
        "filename": "getyourguide.jpg"
    }

    response = requests.post(url_media, json=payload, headers=headers)
    print("Mensagem enviada!")

else:
    print("Fora do dia de envio Get Your Guide!")

Mensagem enviada!

## Transferências Bonificadas

In [ ]:
if hora_atual in(11, 12) or hora_atual in(17, 18): #Enviando 11h e 17h

  import requests
  from bs4 import BeautifulSoup
  from openai import OpenAI
  import re
  import json
  from datetime import datetime
  from zoneinfo import ZoneInfo
  import os
  import gspread
  from oauth2client.service_account import ServiceAccountCredentials

  # =========================================
  # 🛠️ FUNÇÕES UTILITÁRIAS - VERSÃO LOCAL (Colab)
  # =========================================
  # def ler_config_local(nome_arquivo):
  #     """Lê um valor de um arquivo .txt local (usado apenas no Colab/local)"""
  #     with open(nome_arquivo, "r") as f:
  #         return f.read().strip()

  # =========================================
  # 🖥️ FAZENDO UPLOAD DOS ARQUIVOS PARA O COLAB - VERSÃO LOCAL (Colab)
  # =========================================

  # from google.colab import files
  # files.upload()  # seleciona todos os .txt e o credenciais.json de uma vez

  # =========================================
  # 🔑 CHAVE DA API DA IA (GPT)
  # =========================================

  # 🐙 VERSÃO GITHUB ACTIONS (ativa)
  client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

  # 🖥️ VERSÃO LOCAL (Colab) — lê a chave do arquivo openai_key.txt
  #client = OpenAI(api_key=open("openai_key.txt").read().strip())

  # =========================================
  # 🔐 GOOGLE SHEETS
  # =========================================

  # 🐙 VERSÃO GITHUB ACTIONS (ativa)
  SHEET_ID = os.environ["SHEET_ID"]

  # 🖥️ VERSÃO LOCAL (Colab)
  #SHEET_ID = ler_config_local("sheet_id.txt")

  def conectar_google_sheets():
      scope = [
          "https://spreadsheets.google.com/feeds",
          "https://www.googleapis.com/auth/drive"
      ]

      # 🐙 VERSÃO GITHUB ACTIONS (ativa)
      creds_dict = json.loads(os.environ["GOOGLE_CREDENTIALS"])
      creds = ServiceAccountCredentials.from_json_keyfile_dict(creds_dict, scope)

      # 🖥️ VERSÃO LOCAL (Colab) — descomenta e comenta o bloco acima para testar local
      #from google.colab import files
      #uploaded = files.upload()  # faz upload do credenciais.json
      #creds = ServiceAccountCredentials.from_json_keyfile_name("credenciais.json", scope)

      client_gs = gspread.authorize(creds)
      spreadsheet = client_gs.open_by_key(SHEET_ID)
      return spreadsheet

  def carregar_feriados(spreadsheet):
      """Carrega a aba Feriados e retorna um dict {date: nome_feriado}"""
      aba = spreadsheet.worksheet("Feriados")
      dados = aba.get_all_values()
      feriados = {}
      for row in dados[1:]:  # pula o cabeçalho
          if len(row) >= 2 and row[0] and row[1]:
              try:
                  data = datetime.strptime(row[0].strip(), "%d/%m/%Y").date()
                  feriados[data] = row[1].strip()
              except ValueError:
                  continue
      return feriados

  def carregar_eventos(spreadsheet):
      """Carrega a aba Eventos e retorna um dict {date: nome_evento}"""
      aba = spreadsheet.worksheet("Eventos")
      dados = aba.get_all_values()
      eventos = {}
      for row in dados[1:]:  # pula o cabeçalho
          if len(row) >= 2 and row[0] and row[1]:
              try:
                  data = datetime.strptime(row[0].strip(), "%d/%m/%Y").date()
                  eventos[data] = row[1].strip()
              except ValueError:
                  continue
      return eventos

  def gravar_no_sheets(spreadsheet, dados_row):
      """Adiciona uma nova linha na aba Base de Dados"""
      aba = spreadsheet.worksheet("Base de Dados")
      aba.append_row(dados_row, value_input_option="USER_ENTERED")
      print("✅ Linha gravada no Google Sheets!")

  # =========================================
  # 🔎 EXTRAÇÃO DE LINKS DE PROMOÇÕES
  # =========================================
  def extrair_links_promocoes():

      # 🐙 VERSÃO GITHUB ACTIONS (ativa)
      url = os.environ["URL_SCRAPING"]
      url_two = os.environ["URL_SCRAPING_TWO"]

      # 🖥️ VERSÃO LOCAL (Colab)
      #url = ler_config_local("url_scraping.txt")
      #url_two = ler_config_local("url_scraping_two.txt")

      headers = {"User-Agent": "Mozilla/5.0"}
      response = requests.get(url, headers=headers)
      soup = BeautifulSoup(response.text, "html.parser")

      links = []
      for a in soup.find_all("a", href=True):
          href = a["href"]
          if (
              url_two in href
              and "pontos" in href
              and not any(x in href for x in ["categoria", "tag", "page", "#"])
          ):
              links.append(href)

      return list(set(links))

  # =========================================
  # 🤖 EXTRAÇÃO COM IA
  # =========================================
  def extrair_com_ia(html_texto):
    from datetime import datetime
    from zoneinfo import ZoneInfo
    hoje = datetime.now(ZoneInfo("America/Sao_Paulo")).strftime("%d/%m/%Y")

    prompt = f"""
    Você é um especialista em milhas aéreas e vai extrair dados importantes e montar uma mensagem que será enviada em um grupo.
    Seja preciso e nunca invente informações que não estejam explícitas no texto.

    ─────────────────────────────────────
    PARCEIRO (banco de origem)
    ─────────────────────────────────────
    - O parceiro é sempre o DE (origem dos pontos) e a companhia aérea/programa é o PARA (destino das milhas).
      Exemplo: ESFERA → GOL (Smiles)
    - Se a promoção tiver apenas 1 parceiro identificável, use o nome dele conforme as regras abaixo.
    - Se tiver exatamente 2 parceiros, cite os dois nomes. Exemplo: ESFERA e Livelo
    - Se tiver 3 ou mais parceiros, use "Vários parceiros".
    - Nunca invente um parceiro se não estiver explícito no texto.
    - Nunca confunda banco com companhia aérea.

    ─────────────────────────────────────
    NOMES PADRONIZADOS
    ─────────────────────────────────────
    - Azul / Tudo Azul → AZUL (Tudo Azul)
    - GOL / Smiles → GOL (Smiles)
    - Latam / Latam Pass → Latam (Latam Pass)
    - Iberia → Iberia Club
    - Livelo → Livelo
    - Qualquer outro → primeira letra maiúscula, restante minúsculo

    ─────────────────────────────────────
    ÍCONES POR COMPANHIA/PROGRAMA DE DESTINO
    ─────────────────────────────────────
    - AZUL (Tudo Azul) → 🔵
    - Latam (Latam Pass) → 🔵
    - ALL Accor → 🔵
    - KrisFlyer → 🔵
    - GOL (Smiles) → 🟠
    - Iberia Club → 🔴
    - Sicredi → 🟢
    - Banco do Brasil / BB → 🟡
    - C6 Bank → ⚫️
    - Qualquer outro → ⚪️

    ─────────────────────────────────────
    DATA DE VALIDADE
    ─────────────────────────────────────
    - A data de hoje é {hoje}. Use esse mês e ano quando o texto informar apenas o dia.
    - A promoção é válida até às 23h59 do dia informado.
    - Não confunda a data de publicação do artigo com a data de validade da promoção.
      A data de validade geralmente aparece como: "promoção se encerra em", "válida até", "transferências até".
    - Se não encontrar nenhuma data de validade no texto, escreva: 📅 Data não informada

    ─────────────────────────────────────
    COMPANHIA AÉREA vs PROGRAMA DE HOTEL
    ─────────────────────────────────────
    - Mostre ✈️ Companhia aérea: somente quando o destino for uma cia aérea.
    - Mostre 🏨 Programa de fidelidade de hotel: somente quando o destino for ALL Accor.
    - NUNCA mostre as duas linhas na mesma mensagem — é sempre uma ou outra.
    - O parceiro NUNCA é Azul/Tudo Azul quando o destino é ALL Accor. Sempre o contrário: parceiro ALL Accor → destino AZUL (Tudo Azul).

    ─────────────────────────────────────
    EXEMPLO PRÁTICO
    ─────────────────────────────────────
    - Padrão fixo: Enviou 10.000 pontos.
    - Calcule o Recebeu com base no bônus máximo informado.
      Exemplo: 100% de bônus → Enviou 10.000 pontos → Recebeu 20.000 milhas.
    - Use ponto como separador de milhar (padrão brasileiro): 20.000, não 20,000.
    - Sempre indique o percentual considerado: "Considerando X% de Bônus".

    ─────────────────────────────────────
    ALERTA FINAL
    ─────────────────────────────────────
    - Sempre inclua o aviso para ler o regulamento antes de participar.

    ─────────────────────────────────────
    TEXTO DA PROMOÇÃO PARA ANALISAR:
    ─────────────────────────────────────
    {html_texto}

    ─────────────────────────────────────
    FORMATO DE SAÍDA (siga exatamente):
    ─────────────────────────────────────

    🔵 Alerta de Transferência Bonificada: C6 BANK para AZUL (Tudo Azul) 🔵
    ━━━━━━━━━━

    🚀 Transfira seus pontos do C6 BANK para o programa Tudo Azul e ganhe milhas bônus!

    🏦 Parceiro: C6 BANK
    ✈️ Companhia aérea: AZUL (Tudo Azul)  [somente quando for cia aérea]
    🏨 Programa de fidelidade de hotel: ALL Accor  [somente quando o destino for ALL Accor]

    🔥 BONIFICAÇÃO: Até 130% de bônus (Consulte as regras para o seu percentual específico)

    📱 EXEMPLO PRÁTICO:
    Enviou: 10.000 pontos C6 BANK
    Recebeu: 23.000 milhas na Azul (Considerando 130% de Bônus)

    📅 Válido até 19/03/2026

    ⚠️ Atenção: Leia o regulamento da promoção antes de participar!
    """

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "Extraia dados de promoções de milhas."},
            {"role": "user", "content": prompt}
        ],
        temperature=0
    )

    return response.choices[0].message.content

  # =========================================
  # 🗓️ FUNÇÕES AUXILIARES DE DATA
  # =========================================
  def nome_dia_semana_pt(data):
      dias = {0: "Segunda-feira", 1: "Terça-feira", 2: "Quarta-feira", 3: "Quinta-feira",
              4: "Sexta-feira", 5: "Sábado", 6: "Domingo"}
      return dias[data.weekday()]

  def nome_mes_pt(data):
      meses = {1: "Janeiro", 2: "Fevereiro", 3: "Março", 4: "Abril",
              5: "Maio", 6: "Junho", 7: "Julho", 8: "Agosto",
              9: "Setembro", 10: "Outubro", 11: "Novembro", 12: "Dezembro"}
      return meses[data.month]

  # =========================================
  # ▶️ EXECUÇÃO PRINCIPAL
  # =========================================
  list_promocao_key = []
  #print(f'Imprimindo a lista na primeira execucao: {list_promocao_key}')

  if __name__ == "__main__":

      # Conecta ao Google Sheets e carrega feriados/eventos uma vez só
      print("📊 Conectando ao Google Sheets...")
      spreadsheet = conectar_google_sheets()
      feriados = carregar_feriados(spreadsheet)
      eventos = carregar_eventos(spreadsheet)
      print(f"✅ {len(feriados)} feriados e {len(eventos)} eventos carregados.")

      links = extrair_links_promocoes()

      for i, link in enumerate(links, start=1):
          print(f"\n{'='*50}")
          #print(f"{i}. {link}")

          headers = {"User-Agent": "Mozilla/5.0"}
          response = requests.get(link, headers=headers)
          soup = BeautifulSoup(response.text, "html.parser")
          html_texto = soup.get_text(separator=" ", strip=True)

          resultado = extrair_com_ia(html_texto)
          msg_link_grupo = f"🔗 Mais informações sobre a promoção: {link}"
          resultado += f"\n\n{msg_link_grupo}\n\n"

          # ── Extrai data de validade ──
          match = re.search(r"\d{2}/\d{2}/\d{4}", resultado)

          if match:
              data_str = match.group()
              data_formatada = datetime.strptime(data_str, "%d/%m/%Y")
              data_promocao = data_formatada.date()
              data_atual = datetime.now(ZoneInfo("America/Sao_Paulo")).date()

              status_promo = "Dentro do prazo" if data_promocao >= data_atual else "Fora do prazo"
          else:
              data_str = None
              data_promocao = None
              status_promo = "Fora do prazo"

          print(f"Status: {status_promo}")

          # ── Alerta de último dia — lógica no Python, não na IA ──
          if data_promocao and data_promocao == data_atual:
            alerta_hoje = "\n\n🚨 ATENÇÃO: Essa promoção acaba HOJE! Corra para aproveitar!\n"
            resultado = re.sub(
                r"(📅 Váli?do? até \d{2}/\d{2}/\d{4})",
                r"\1" + alerta_hoje,
                resultado
            )

          # ── Extrai campos da mensagem ──
          parceiro = re.search(r"🏦 Parceiros?:\s*(.+)", resultado)
          parceiro = parceiro.group(1).strip() if parceiro else None

          cia = re.search(r"✈️ Companhia aérea:\s*(.+)", resultado)
          cia = cia.group(1).strip() if cia else None

          # Tenta pegar programa de hotel se não tiver cia aérea
          if not cia:
              hotel = re.search(r"🏨 Programa de fidelidade de hotel:\s*(.+)", resultado)
              cia = hotel.group(1).strip() if hotel else None

          bonus = re.search(r"BONIFICAÇÃO:.*?(\d+)%", resultado)
          bonus_str = bonus.group(1) + "%" if bonus else None
          bonus_num = int(bonus.group(1)) if bonus else None

          # ── Link Clube Azul — lógica no Python, não na IA ──
          LINK_CLUBE_AZUL = "https://apps.voeazul.com.br/TudoAzulClub/share-mgm.html?hash=7uhPhMsj%2B2YY%2Bczpr2ebrxpa6feTjo%2F5yu2MJlXj4ysc-aC"
          TEXTO_CLUBE_AZUL = f"\n💰 Assine o Clube Azul com o nosso link para ganhar a bonificação maior + 1.000 milhas bônus (a gente também ganha esse bônus): {LINK_CLUBE_AZUL}\n\n"

          if cia and "azul" in cia.lower():
              resultado = resultado.replace(
                  "🔥 BONIFICAÇÃO:",
                  TEXTO_CLUBE_AZUL + "🔥 BONIFICAÇÃO:"
              )

          # ── Monta a chave anti-duplicata ──
          parceiro_key = parceiro or ""
          cia_key = cia or ""
          data_key = data_str or ""
          promocao_key = (parceiro_key + cia_key + data_key).replace(" ", "")

          cont = 0
          # ── Processa e envia somente se válida e não duplicada ──
          if promocao_key not in list_promocao_key and status_promo == "Dentro do prazo":
              list_promocao_key.append(promocao_key)
              #print(f'Lista atualizada ({i}ª execução): {list_promocao_key}')

              # 🖥️ VERSÃO LOCAL (Colab) — lê dos arquivos .txt
              #id_grupo_envio = ler_config_local("id_grupo.txt") #grupo original promos
              # id_grupo_envio = ler_config_local("id_grupo_teste.txt") #grupo pessoal para testes
              # INSTANCE_ID    = ler_config_local("instance_id.txt")
              # API_KEY        = ler_config_local("api_key.txt")

              # 🐙 VERSÃO GITHUB ACTIONS — descomenta e comenta o bloco acima
              id_grupo_envio = os.environ["ID_GRUPO_MILHAS"] #ID_GRUPO_PESSOAL_TESTES
              INSTANCE_ID    = os.environ["INSTANCE_ID"]
              API_KEY        = os.environ["API_KEY"]

              url_ws = f"https://api.zapperapi.com/{INSTANCE_ID}/messages/text"
              headers_ws = {
                  "X-Api-Key": API_KEY,
                  "Content-Type": "application/json"
              }
              payload = {
                  "jid": id_grupo_envio,
                  "message": resultado,
              }
              response_ws = requests.post(url_ws, json=payload, headers=headers_ws)
              print("📨 Promoção enviada no grupo!")

              # ── Monta ID da promoção ──
              # Formato: parceiro-cia-bonus-Valido até DD/MM/YYYY
              parceiro_slug = (parceiro or "").lower().replace(" ", "-")
              cia_slug = (cia or "").lower().replace(" ", "-")
              bonus_slug = str(bonus_num) if bonus_num else "0"
              data_slug = f"Valido ate {data_str}" if data_str else "sem-data"
              id_promocao = f"{parceiro_slug}-{cia_slug}-{bonus_slug}-{data_slug}"

              # ── Data/hora de gravação ──
              agora = datetime.now(ZoneInfo("America/Sao_Paulo"))
              data_hora_str = agora.strftime("%d/%m/%Y %H:%M:%S")
              data_hoje = agora.date()
              nome_dia = nome_dia_semana_pt(agora)
              nome_mes = nome_mes_pt(agora)

              # ── Verifica feriado e evento ──
              flag_feriado = 1 if data_hoje in feriados else 0
              nome_feriado = feriados.get(data_hoje, "")

              flag_evento = 1 if data_hoje in eventos else 0
              nome_evento = eventos.get(data_hoje, "")

              # ── Texto original resumido (primeiros 500 chars do html) ──
              texto_original = html_texto[:500].replace("\n", " ").strip()

              # ── Monta a linha para gravar ──
              linha = [
                  data_hora_str,                          # data_hora
                  agora.strftime("%d/%m/%Y"),             # data
                  nome_dia,                               # nome_dia_semana
                  nome_mes,                               # nome_mes
                  id_promocao,                            # id_promocao
                  parceiro or "",                         # parceiro_origem
                  cia or "",                              # companhia_aera_destino
                  bonus_str or "",                        # perc_bonus
                  bonus_num or 0,                         # bonus_normalizado
                  data_str or "",                         # data_max_promocao
                  flag_feriado,                           # flag_feriado
                  nome_feriado,                           # nome_feriado
                  flag_evento,                            # flag_dia_evento
                  nome_evento,                            # nome_evento
                  texto_original,                         # texto_original
                  link                                    # link_promocao
              ]

              # ── Grava no Google Sheets ──
              gravar_no_sheets(spreadsheet, linha)
          else:
              print("⚠️  Promoção duplicada e/ou fora do prazo — ignorada.")

##Configuração para testes na máquina local

In [ ]:
# =========================================
# 🛠️ FUNÇÕES UTILITÁRIAS - VERSÃO LOCAL (Colab)
# =========================================

if 1==2:
  #Buscando a hora atual
  agora_brasilia = datetime.datetime.now(ZoneInfo("America/Sao_Paulo"))

  hora_atual = int(agora_brasilia.strftime("%H"))

  from google.colab import files
  files.upload()  # seleciona o id_grupo_teste.txt (e qualquer outro .txt que precisar)

  def ler_config_local(nome_arquivo):
    """Lê um valor de um arquivo .txt local (usado apenas no Colab/local)"""
    with open(nome_arquivo, "r") as f:
      return f.read().strip()

    # 🖥️ VERSÃO LOCAL (Colab) — lê dos arquivos .txt
  #id_grupo_envio = ler_config_local("id_grupo.txt") #grupo original promos
  id_grupo_envio = ler_config_local("id_grupo_teste.txt") #grupo pessoal para testes
  print(f"Grupo de envio {id_grupo_envio}")

  INSTANCE_ID    = ler_config_local("instance_id.txt")
  API_KEY        = ler_config_local("api_key.txt")

  # Endpoint
  url = f"https://api.zapperapi.com/{INSTANCE_ID}/messages/text" #url para mensagens de texto
  url_media = f"https://api.zapperapi.com/{INSTANCE_ID}/messages/media" #url para mensagens de texto com imagens

  headers = {
      "X-Api-Key": API_KEY,
      "Content-Type": "application/json"
  }

nao e